build/Makefile.components
source/code/providers/support/productdependencies.cpp

Add hostname to SCX log file header

---

installer/bundle/bundle_skel.sh

Modify to not upgrade to same version of kit already installed

---

installer/bundle/bundle_skel.sh

Initialize installer properly in shell bundle or --version-check fails

---

installer/datafiles/Base_SCXCore.data

Don't echo '-n' on platforms that don't support 'echo -n' during install

---

installer/datafiles/Base_SCXCore.data

Add sysdir to appropriate shared directories for installbuilder

---

installer/bundle/bundle_skel_AIX.sh
installer/bundle/bundle_skel_HPUX.sh
installer/bundle/bundle_skel_Linux.sh
installer/bundle/bundle_skel_SunOS.sh
installer/bundle/create_bundle.sh

bundle_skel.sh is split into
* installer/bundle/bundle_skel_AIX.sh
* installer/bundle/bundle_skel_HPUX.sh
* installer/bundle/bundle_skel_Linux.sh
* installer/bundle/bundle_skel_SunOS.sh
Change Linux bundle to install/upgrade all packages as a set

Split bundle_skel.sh into bundle_skel_<PLATFORM>.sh

---

test/code/providers/runas_provider/runasprovider_test.cpp

Fix SCXRunAsProviderTest::TestChRoot to run properly on AIX

---

build/Makefile.providers

Fix make target "omi_reg" for new directory locations from Jenkins

---

README.md
build/Makefile
test/code/providers/os_provider/osprovider_test.cpp

Get Travis set up for use (enabled with checkin of .travis.yaml, coming soon)

---

README.md

Added enumeration output to README.md file

---

README.md

Fix bad link to OMI project (referred to Travis)

---

README.md

Add enumeration detail for SCX_Application_Server

---

source/code/providers/support/runasprovider.cpp

Fix spacing in RunAsProvider::ExecuteScript method

---

source/code/providers/support/runasprovider.cpp

Delete script file even if a timeout occurs (exception thrown)

---

test/util/artifacts/runas-memleak/README.md
test/util/artifacts/runas-memleak/measureleak.sh
test/util/artifacts/runas-memleak/testleak.sh

Add tools useful to test for memory leaks in the RunAs provider
(fix committed in commit hash 5a46df0).
@OpusDude

Tools useful to test leak in the RunAs provider

---

installer/bundle/bundle_skel_Linux.sh

Resolve problem where software version is not upgraded in error
@vimish 

Fix comparsion in function check_version_installable

---

test/util/artifacts/runas-memleak/README.md
test/util/artifacts/runas-memleak/measureleak.sh
test/util/artifacts/runas-memleak/testleak.sh

- Added support for UNIX.
- Added ExecuteShell and ExecuteCommand.
@jeffaco

runas-memleak artifacts

---

.travis.yml

Update Travis CI to use appropriate components for 2016-URNext branch

---

source/code/shared/tools/scx_ssl_config/scx_ssl_config.cpp

@mabicca @Microsoft/ostc-devs 
https://github.com/Microsoft/OMS-Agent-for-Linux/issues/241

Capture new error SCXErrnoERANGE_Exception for meaningful error

---

build/Makefile.pf.Linux
test/code/providers/runas_provider/runasprovider_test.cpp

Add support for Power8

---

build/configure

Linux AIX PPC builds should not try to build universally

---

build/Makefile.kits
installer/bundle/bundle_skel_PPC-RHEL.sh
installer/bundle/create_bundle.sh

Changes:
----------
Makefile.kits :  Calling the create_bundle.sh file with the DISTRO as 'PPC-RHEL' so that the correct bundle can be generated based on bundle_skel_PPC-RHEL.sh
create_bundle.sh : Added support for the ppc RHEL Linux.
bundle_skel_PPC-RHEL.sh : This skel file will be generated as the SH Module for the RHEL PPC.
@Microsoft/ostc-devs  @jeffaco

 Nirsingh power8 scx

---

build/Makefile.kits

(Synchronize with PAL changes)

Allow PPC builds to be identified as REDHAT, not ULINUX

---

build/Makefile.kits
build/Makefile.pf.Linux
build/configure
installer/bundle/bundle_skel_PPC-RHEL.sh
installer/bundle/create_bundle.sh
test/code/providers/runas_provider/runasprovider_test.cpp

Merging the following transactions from the master branch.
c93d57e
f97b12a
e025fc8
76e73e5
c54bdf1
0488bff
@jeffaco

Enable Shell Bundle Generation for Power8 on 2016-URNEXT

---

source/code/providers/support/appserver/appserverenumeration.cpp
source/code/providers/support/appserver/jbossappserverinstance.cpp
source/code/providers/support/appserver/jbossappserverinstance.h
test/code/providers/appserver_provider/appserverenumeration_test.cpp
test/code/providers/appserver_provider/jbossappserverinstance_test.cpp

Backport JBoss non default config fix from master to 2016-URNext

Fix non default config in JBoss 7

---

source/code/providers/SCX_UnixProcess_Class_Provider.cpp

Add log messages for posting process instance to OMI

---

installer/bundle/bundle_skel_Linux.sh

@lagalbra
If upgrade of scx or omi package fails then remove the packages and reinstall.

Remove and reinstall packages if upgarde fails

---

installer/bundle/bundle_skel_AIX.sh
installer/bundle/bundle_skel_HPUX.sh
installer/bundle/bundle_skel_Linux.sh
installer/bundle/bundle_skel_SunOS.sh
source/code/providers/support/appserver/websphereappserverinstance.cpp

Porting unix bundle and websphere fixes to 2016 UR

Vimish bundle ur

---

source/code/providers/support/metaprovider.cpp

SCOM CB release will ship omsagent bundle instead of scx bundle on
Linux platform. SCOM console needs to report omsagent version as
the installed agent version.
kitVersionString's value in SCX_Agent enumeration is shown in SCOM
console. Change is made to check if omsagent install info file is
present or not. If present it will be parsed to get the value of
install version and install time. If not scx install info file
will continue to be used.
This change is only for SCOM CB release. 2016 UR's will remain
on current implementation.

Report omsagent version, if installed, in SCX_Agent's kitVersionString

---

build/Makefile.kits

SCX package created for x86 platform missing apache, MySQL kits.

scx package for x86 platform missing OSS kits.

---

source/code/shared/tools/scx_ssl_config/scx_ssl_config.cpp

When upgrading from 2012 R2 to latest scx omikey ownership
is not getting updated to omi:omi. Due to this omi is not
able to read the key file, hence port 1270 is getting closed.
To address this scxsslconfig is updated to check and update
omikey ownership if key file alreday exists.

Update omikey ownership to omi:omi during scx upgrade.

---

installer/datafiles/Linux.data

Instead of fix time making changes that will check log file size in every 4 hr. If log size has crossed the size threshold it will rotate.

LogRotate Support in SCX

---

installer/conf/scxenum.conf
installer/datafiles/Linux.data

Add scxenum.conf during installation.

Create scxenum config file

---

installer/datafiles/Linux.data

Fixes scx part of suse11 openssl1 issue

Fixes suse11 openssl1 issue

---

installer/datafiles/Linux.data

@sarojcare I am not familiar with SCX code, maybe you can have a check if I do correct modification or wrong modification? thank you!

Set scx logrotate state file

---

installer/datafiles/Linux.data

@microsoft/omi-devs fixes #168, and this PR needs review
this PR contains below 2 fixes:
1. Fixes scxagent logrotate files removed for scx upgrade
2. Fixes scxagent-logrotate semodule removed for scx upgrade

Fixes logrotate and semodule upgrade issue

---

build/Makefile.kits

This PR fixes debug build flow to previous behavior.
@deepakjain111 needs help review, thank you!

Fixes debug build flow to previous behavior

---

build/Makefile.kits

This PR adds back packages in the release folder. @deepakjain111

Keep consistent binaries and packages for debug and release

---

installer/datafiles/Linux.data

* Fixes issue when semodule installs fail.
* Update Linux.data selinux fail logic.

1.7.1-0 release 
