microsoft/SCXcore

- .gitmodules
- build/Makefile.kits
(Difficult to manage tips properly; will be tracked by superproject)
This PR will relocate installer/oss-kits to <super-project>/opsmgr-kits. Note that this new super project is already committed to both Build-SCXcore and Build-OMS-Agent-for-Linux projects. Once this is committed, the change will actually take effect.
I'm uncertain how to get the new subproject without a new clone. For simplicity, I'll just suggest that people clone the repo again (trivial with pbuild, just throw on `--clone`), which absolutely works.
@Microsoft/ostc-devs @Microsoft/omsagent-devs
> Remove oss-kits as SCXcore submodule (already added to superprojects

- build/Makefile
- build/Makefile.kits
Makefile - Add SHELL=/bin/bash.  Debian variants default to /bin/sh, which breaks brace expansion.
Makefile.kits - Do not set DPKG_LOCATION if /usr/bin/dpkg is present.
@jeffaco 
@niroyb
> Changes for building local and ULINUX on Debian/Ubuntu:

- installer/datafiles/Base_SCXCore.data
Azure agents never require the agent to listen on port 1270. Rather
than building a special kit for Azure, check for marker file and, if
it exists, don't enable the port 1270 listener.
https://github.com/Microsoft/OMS-Agent-for-Linux/issues/102
> Allow file /etc/scxagent-disable-port to disable port 1270 listener

- installer/bundle/bundle_skel_Linux.sh
Upgrade path is fixed so that omi is installed if not found.
> Fix broken upgrade on linux

- README.md
- build/Makefile.gcc3
- build/configure
- test/code/providers/os_provider/osprovider_test.cpp
Rather than looking up environment variables in code each time we
need to detect travis, #define TRAVIS so consumers can easily
determine if special Travis CI handling is needed.
> Improve Travis Continuous Integration Detection Logic

- source/code/providers/SCX_OperatingSystem_Class_Provider.cpp
Commit hash 0921ef7 (back in 2013) incorporated a memory leak of the
SCXThread object. This was "fixed" in f004d08, which was supposed to
roll back other changes to the SCX_OperatingSystem_Class_Provider.cxx
and then fix the bug.
However, it turns out that the fixes never made it past the rollback.
This commit fixes those leaks for real.
Note: I have some test files that will be checked in tomorrow. I want to get this in for tonight's build.
> Resolve memory leak in RunAs provider (SCXThread object leaking)

- source/code/providers/support/appserver/appserverenumeration.cpp
- source/code/providers/support/appserver/jbossappserverinstance.cpp
- source/code/providers/support/appserver/jbossappserverinstance.h
- test/code/providers/appserver_provider/appserverenumeration_test.cpp
- test/code/providers/appserver_provider/jbossappserverinstance_test.cpp
For standalone mode JBoss 7 allows use of some non default config file (standalone-full.xml, standalone-ha.xml etc) . Our current code only considers default stanalone.xml file. Hence when JBoss starts with non default config file it was getting wrongly interpreted as Jboss 4, 5 or 6 which resulted in wrong install path for that JBoss instance.
> Fix non default config in JBoss 7

- build/Makefile
- build/Makefile.components
- build/configure
@Microsoft/ostc-devs @Microsoft/omi-devs 
First stab at OMI building it's own packages. This is tested on Linux and appears to work fine, running a pbuild now for platform breadth.
Note that this shelveset is designed to work in concert with OMI changes as well, review that as well please.
> Integrate with new OMI build process (--enable-microsoft)

- installer/bundle/bundle_skel_PPC-RHEL.sh
Checking for existance of uninstall folder's (/opt/microsoft/scx/bin/uninstall) existance before deleting it.
@jeffaco
> Check that uninstall script exists prior to trying to execute it

- source/code/shared/tools/scx_ssl_config/scx_ssl_config.cpp
- source/code/shared/tools/scx_ssl_config/scxsslcert.cpp
- source/code/shared/tools/scx_ssl_config/scxsslcert.h
- test/code/shared/tools/scx_ssl_config/scxsslcert_test.cpp
Added new flag -c in scxsslconfig tool to signify client cert generation.
Passing this flag will instruct the tool to add clientAuth EKU to the certificate.
This along with [-g targetpath] option will be used to generate a cert and key that will be used for enhanced log monitoring feature.
Sample command:
scxsslconfig -c -g <Path to cert location>
> Added support in scxsslconfig to generate client auth certificate

- source/code/providers/SCX_Agent_Class_Provider.cpp
- source/code/providers/SCX_Application_Server_Class_Provider.cpp
- source/code/providers/SCX_DiskDriveStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_DiskDrive_Class_Provider.cpp
- source/code/providers/SCX_EthernetPortStatistics_Class_Provider.cpp
- source/code/providers/SCX_FileSystemStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_FileSystem_Class_Provider.cpp
- source/code/providers/SCX_IPProtocolEndpoint_Class_Provider.cpp
- source/code/providers/SCX_LANEndpoint_Class_Provider.cpp
- source/code/providers/SCX_LogFile_Class_Provider.cpp
- source/code/providers/SCX_MemoryStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_OperatingSystem_Class_Provider.cpp
- source/code/providers/SCX_ProcessorStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_RTProcessorStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_UnixProcessStatisticalInformation_Class_Provider.cpp
- source/code/providers/SCX_UnixProcess_Class_Provider.cpp
Add logging to isolate if a class within a process is hanging.
NOTE: One of the routines was reformatted for standard indentation. Add `?w=1` to review line to ignore spacing to avoid flagging these as changes.
@Microsoft/ostc-devs  @johnkord @Microsoft/omi-devs
> Add logging to show entry/exit into enumeration classes

- build/Makefile
- build/Makefile.kits
- installer/bundle/bundle_skel_AIX.sh
- installer/bundle/bundle_skel_HPUX.sh
- installer/bundle/bundle_skel_Linux.sh
- installer/bundle/bundle_skel_PPC-RHEL.sh
- installer/bundle/bundle_skel_SunOS.sh
- installer/datafiles/Base_SCXCore.data
@lagalbra
scx will no longer build omi packages. Instead it will
take the omi packages from the omi-kits repo where omi
team will check in latest certified omi packages for all
platforms.
> Pick OMI packages from omi-kits repo

- installer/bundle/bundle_skel_AIX.sh
Issue : After upgrading the OM agent from 2012 to 2016 on AIX platform, the Omiserver is still running under "/opt/microsoft/scx/bin/" where as it should be running under "/opt/omi/bin/"
Analysis : On the 2012 OM agent we do not have omi.rte and hence when we check if the omi.rte is already installed, the check fails and omi (2016) is installed, but it does not kill the omiserver process running from "/opt/microsoft/scx/bin/"
Fix : We should stop the 2012 agent (scx.rte) before upgrading to 2016.
Note:
Tried analyzing to place the fix to other appropriate place, but do not see any other place in the code where this can be handled. eg DataFiles 
@ostc-devs
> Fix Omiserver is still running under "/opt/microsoft/scx/bin/" after upgrade OM agent from 2012 to 2016

- installer/bundle/bundle_skel_AIX.sh
- installer/bundle/bundle_skel_HPUX.sh
- installer/bundle/bundle_skel_Linux.sh
- installer/bundle/bundle_skel_SunOS.sh
Installed omi was getting downgraded during shell bundle install and upgrade on unix.
Also version check of omi was not done during install on Linux.
Added version checks to resolve the issue.
> Fix version checks in shell bundle install and upgrade

- source/code/providers/support/appserver/websphereappserverinstance.cpp
To check whether a websphere is still installed, presence
of file wsBundleMetadata is checked. Atleast on websphere
8.5.x wsBundleMetadata is a directory.
Updated the method to check for the presence of directory.
Also did not remove the file check to avoid any backward
compatibility issues.
> Fix IsStillInstalled check for websphere 8.5.x

- installer/bundle/bundle_skel_Linux.sh
- installer/conf/uninstall
@lagalbra
Uninstall script should be used remove packages
during upgrade failure recovery. Since scx and
omi have to be forcibly removed, uninstall script
is updated to accept force parameter.
Also if uninstall script is not present then install
check will not be performed before removing the scx
and omi packages.
> Add force option in scx uninstall script

- source/code/shared/tools/scx_ssl_config/scx_ssl_config.cpp
This change will set ownership for certificate files to omi:omi.
Test:
pbuild passed.
Installed on AIX 6, Solaris 5.11, HPUX 11.31 and SUSE 10. After installation omiengine comes up.
Verified the ownership omikey.pem file which is set to omi:omi.
> Set ownership of omikey.pem file to omi:omi

- source/code/shared/tools/scx_ssl_config/scx_ssl_config.cpp
- source/code/shared/tools/scx_ssl_config/scxsslcert.h
This change set includes
1. Different way to handle the error cases in pbuild and product deployment environment.
2. Calling new exception handler to print the exception appropriately.
eg.
"Calling getpwnam() with user name parameter "omi", returned an error with errno = 1(Operation not permitted )"
> Fixing the issue when omi user profile does not exist on system

- installer/datafiles/Linux.data
@narinem
While upgrading omsagent, azure linux extension calls --remove
followed by --install, instead of directly calling --upgrade.
This sequence was causing port 1270 to close as we close the
port on uninstall and do not open it by default on install.
To support this scenario we will now check if port 1270 is
open at uninstall. If yes we will create a marker file in
scx conf directory. On install if the marker file is present
then port 1270 will be opened.
As marker file is created in scx conf directory, it will get
deleted in --purge call.
> Open port 1270 on install if it was open at uninstall

- source/code/providers/support/appserver/appserverenumeration.cpp
- source/code/providers/support/appserver/jbossappserverinstance.cpp
- source/code/providers/support/appserver/jbossappserverinstance.h
- test/code/providers/appserver_provider/appserverenumeration_test.cpp
- test/code/providers/appserver_provider/jbossappserverinstance_test.cpp
JBoss standalone mode allows multiple instances to run using same
Jboss home dir. To support this Key and Diskpath is set to the
complete configuration file used for the instance.
Also same configuration file can be used for different instances
by giving diffrenet port offset. The code is updated to check
for port offset in command line parameters. If present it will
be appended to Key and Diskpath to uniquely identify the instance.
JBoss does not mandate that standalone should be a directory in
configuration path. Updated the agent to pass detected deployment type
from appserver enumeration to JBoss instance. Value of deployment type
will be used to determine if it is an JBoss standalone instance.
This fix is validated in customer's env.
> Support multiple JBoss standalone instances with same home directory

- test/code/shared/tools/scx_ssl_config/scxsslcert_test.cpp
Punnycode conversion of international domain name is returning
unexpected output on solaris 11 x86. This is causing test
failure in SCX SSL certificate test.
Disabling the test so that build can go through.
> Fix unittest failure on solaris 11 x86.

- .travis.yml
- build/Makefile.kits
- installer/conf/logrotate.conf
- installer/datafiles/Linux.data
- installer/datafiles/Linux_RPM.data
Previously logrotate sepolicy module was created only for RPM based platforms so that logrotate utility has sufficient security context to rotate scx.log. Same is needed for deb based platform as well.
> Create selinux module for logrotate feature on debian platform

- source/code/providers/support/metaprovider.cpp
Starting from CB3 omsagent will no longer be shown as agent version.
scx version will be used instead.
> Revert reporting omsagent version

- source/code/providers/support/appserver/jbossappserverinstance.cpp
Wildfly 9 onwards version is written as wildfly-version-1.0...,
where 1 corresponds to 9. To handle this we are adding 8 to the
major version so that port information can be retrieved correctly.
> Handle Wildfly 9+ releases.

- installer/datafiles/Linux.data
Since 2016URNext code is different with master, I have cherrypick from master, and new this PR.
> Fixes suse11 openssl1 issue

- source/code/providers/SCX_LANEndpoint_Class_Provider.cpp
Change is to pass all type of query for default handling other than the single instance query which is of interest from SCOM prospective.
> Parse specific patteren, pass rest to comply with existing behavior

- source/code/providers/SCX_FileSystemStatisticalInformation_Class_Provider.cpp
SCX provider does not handle reserve memory at file system level same as Linux command 'df' handles, which causes difference in  memory related parameters in SCX_FileSystemStatisticalInformation enumeration query. This PR takes care of that issue.
> File system's memory related parameter is different from Linux command DF
